AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: BpmPeopleTime

Resources:

  PeopleTimeApiLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.ioet.bpm.people-time.aws.handler.AwsLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: build/distributions/bpm-people-time-api-0.0.1.zip
      MemorySize: 1512
      Role: arn:aws:iam::524819651720:role/API-lambda-deployment
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  PeopleTimeApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/people-time'
    Export:
      Name: PeopleTimeApi