AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: BpmPeopleTime

Parameters:
  ApiEnvironment:
    Type: String
    Default: PeopleTimeProduction
    AllowedValues:
      - PeopleTimeStaging
      - PeopleTimeProduction
    Description: Enter Staging or Development. Default is PeopleTimeProduction.

Resources:
  PeopleTimeApiLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.ioet.bpm.peopletime.aws.handler.AwsLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: build/distributions/bpm-people-time-api-0.0.1.zip
      MemorySize: 2048
      Role: arn:aws:iam::524819651720:role/API-lambda-deployment
      Timeout: 300
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  PeopleTimeApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage'
    Export:
      Name: !Ref ApiEnvironment
