package com.ioet.bpm.peopletime.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotBlank;
import java.util.Date;

@NoArgsConstructor
@Data
@DynamoDBTable(tableName = "time_event")
public class TimeEvent {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @NotBlank
    @DynamoDBAttribute
    private String personId;

    @DynamoDBAttribute
    private String organizationId;

    @NotBlank
    @DynamoDBAttribute
    private String projectId;

    @DynamoDBAttribute
    private String activity;

    @NotBlank
    @DynamoDBAttribute
    private String templateId;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Date startTime;

    @DynamoDBAttribute
    private Date stopTime;

    public TimeEvent(TimeTemplate timeTemplate) {
        this.personId = timeTemplate.getPersonId();
        this.organizationId = timeTemplate.getOrganizationId();
        this.projectId = timeTemplate.getProjectId();
        this.activity = timeTemplate.getActivity();
        this.templateId = timeTemplate.getId();
    }
}
