package com.ioet.bpm.peopletime.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotBlank;

@NoArgsConstructor
@Data
@DynamoDBTable(tableName = "time_template")
public class TimeTemplate {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @NotBlank
    @DynamoDBAttribute
    private String name;

    @NotBlank
    @DynamoDBAttribute
    private String personId;

    @DynamoDBAttribute
    private String customerId;

    @NotBlank
    @DynamoDBAttribute
    private String projectId;

    @DynamoDBAttribute
    private String activity;
}
