package com.ioet.bpm.peopletime.timeevents.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.ioet.bpm.peopletime.skills.domain.Skill;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotBlank;
import java.util.Date;
import java.util.List;

@NoArgsConstructor
@AllArgsConstructor
@Builder
@Data
@DynamoDBTable(tableName = "people_time_time_event")
public class TimeEvent {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @NotBlank
    @DynamoDBAttribute
    private String personId;

    @NotBlank
    @DynamoDBAttribute
    private String organizationId;

    @NotBlank
    @DynamoDBAttribute
    private String organizationName;

    @NotBlank
    @DynamoDBAttribute
    private String projectId;

    @NotBlank
    @DynamoDBAttribute
    private String projectName;

    @NotBlank
    @DynamoDBAttribute
    private String activity;

    @DynamoDBTypeConvertedJson
    @DynamoDBAttribute
    private List<Skill> skills;

    @DynamoDBAttribute
    private String note;

    @NotBlank
    @DynamoDBAttribute
    private String templateId;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Date startTime;

    @DynamoDBAttribute
    private Date stopTime;

    public TimeEvent(String userId) {
        this.personId = userId;
    }
}
