package com.ioet.bpm.peopletime.timeevents.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.ioet.bpm.peopletime.timetemplates.domain.TimeTemplate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotBlank;
import java.util.Date;

@NoArgsConstructor
@AllArgsConstructor
@Builder
@Data
@DynamoDBTable(tableName = "people_time_event")
public class TimeEvent {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @NotBlank
    @DynamoDBAttribute
    private String personId;

    @DynamoDBAttribute
    private String organizationId;

    @NotBlank
    @DynamoDBAttribute
    private String projectId;

    @DynamoDBAttribute
    private String activity;

    @DynamoDBAttribute
    private String note;

    @NotBlank
    @DynamoDBAttribute
    private String templateId;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Date startTime;

    @DynamoDBAttribute
    private Date stopTime;

    public TimeEvent(TimeTemplate timeTemplate, String userId) {
        this.personId = userId;
        this.organizationId = timeTemplate.getOrganizationId();
        this.projectId = timeTemplate.getProjectId();
        this.activity = timeTemplate.getActivity();
        this.templateId = timeTemplate.getId();
    }
}
